name: Generate Snake Animation

on:
  # Runs automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"

  # Allows manual trigger
  workflow_dispatch:

  # Runs on push to the main branch
  push:
    branches:
      - main  # Change this if your default branch is 'master'

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate GitHub Contribution Grid Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: chama-x  # Change this to your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Debugging step: Check if files were created
      - name: List output files
        run: |
          mkdir -p dist  # Ensure folder exists
          ls -la dist

      # Push the SVG files to the gh-pages branch
      - name: Deploy Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages  # GitHub Pages branch
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
